[package]
name = "stemmers"
version = "0.1.0"
edition = "2021"
authors = ["Nando Vieira <me@fnando.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
rust-stemmers = "1.2.0"
whatlang = "0.16.4"
